- type: job
  id: ESChemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: ESJobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
  startingGear: ESChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ESChemistGear
  equipment:
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorBlue
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    jumpsuit: ClothingUniformJumpsuitChemistry
    outerClothing: ClothingOuterCoatLabChemOpened
    back: ClothingBackpackChemistry
    pocket1: HandLabeler