- type: job
  id: ESMedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: ESJobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2.5h
  startingGear: ESDoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: ESDoctorGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalPDA
    gloves: ClothingHandsGlovesColorBlue
    head: ClothingHeadHatSurgcapBlue
    mask: ClothingMaskSterile
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    outerClothing: ClothingOuterCoatLabOpened
    back: ClothingBackpackMedical