- type: job
  id: ESScientist
  name: job-name-scientist
  description: job-description-scientist
  suffix: ES
  playTimeTracker: ESJobScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 2.5h
  startingGear: ESScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ESScientistGear
  equipment:
    shoes: ClothingShoesChef
    id: SciencePDA
    neck: ClothingNeckTieSci
    ears: ClothingHeadsetScience
    jumpsuit: ClothingUniformJumpsuitScientist
    outerClothing: ClothingOuterCoatLabOpened
    back: ClothingBackpackScience