- type: job
  id: ESDetective
  name: job-name-detective
  description: job-description-detective
  suffix: ES
  playTimeTracker: ESJobDetective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 5h
  startingGear: ESDetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ESDetectiveGear
  equipment:
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHatFedoraBrown
    neck: ClothingNeckTieDet
    belt: ClothingBeltHolsterFilled
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ClothingOuterCoatDetectiveLoadout
    back: ClothingBackpackSecurity
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner