- type: job
  id: ESWarden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: ESJobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
  weight: 5
  startingGear: ESWardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ESWardenGear
  equipment:
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    outerClothing: ClothingOuterCoatWarden
    back: ClothingBackpackSecurity
    pocket1: ESWeaponHybridTaser
  storage:
    back:
    - Flash