- type: job
  id: ESCaptain
  name: job-name-captain
  description: job-description-captain
  suffix: ES
  playTimeTracker: ESJobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 4h
  weight: 20
  startingGear: ESCaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ESCaptainGear
  equipment:
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    jumpsuit: ClothingUniformJumpsuitCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    back: ClothingBackpackCaptain
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: ESCaptainChameleonOutfit
  job: ESCaptain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
