- type: job
  id: ESStationEngineer
  name: job-name-engineer
  description: job-description-engineer
  suffix: ES
  playTimeTracker: ESJobStationEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2.5h
  startingGear: ESStationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: ESStationEngineerGear
  equipment:
    shoes: ClothingShoesColorOrange
    eyes: ClothingEyesGlassesMeson
    id: EngineerPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    outerClothing: ClothingOuterVestHazard

- type: chameleonOutfit
  id: ESStationEngineerChameleonOutfit
  job: ESStationEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
