- type: job
  id: ESBartender
  name: job-name-bartender
  description: job-description-bartender
  suffix: ES
  playTimeTracker: ESJobBartender
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0.5h
  startingGear: ESBartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: ESBartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
    head: ClothingHeadHatTophat
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVest
    back: ClothingBackpack

- type: chameleonOutfit
  id: ESBartenderChameleonOutfit
  job: ESBartender
  equipment:
    head: ClothingHeadHatTophat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedBlack
    outerClothing: ClothingOuterArmorBasicSlim
    gloves: ClothingHandsGlovesColorBlack

