- type: job
  id: ESBotanist
  name: job-name-botanist
  description: job-description-botanist
  suffix: ES
  playTimeTracker: ESJobBotanist
  startingGear: ESBotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: ESBotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
    jumpsuit: ClothingUniformJumpsuitHydroponics
    outerClothing: ClothingOuterApronBotanist
    back: ClothingBackpackHydroponics

- type: chameleonOutfit
  id: ESBotanistChameleonOutfit
  job: ESBotanist
  equipment:
    head: ClothingHeadBandBotany
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterApronBotanist
    gloves: ClothingHandsGlovesLeather
