- type: job
  id: ESCargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  suffix: ES
  playTimeTracker: ESJobCargoTechnician
  startingGear: ESCargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: ESCargoTechGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpack

- type: chameleonOutfit
  id: ESCargoTechnicianChameleonOutfit
  job: ESCargoTechnician
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
