- type: job
  id: ESSalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  suffix: ES
  playTimeTracker: ESJobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 2.5h
  icon: "JobIconShaftMiner"
  startingGear: ESSalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: ESSalvageSpecialistGear
  equipment:
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvage