- type: job
  id: ESPassenger
  name: job-name-passenger
  description: job-description-passenger
  suffix: ES
  playTimeTracker: ESJobPassenger
  startingGear: ESPassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: ESPassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpack

- type: chameleonOutfit
  id: ESPassengerChameleonOutfit
  job: ESPassenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
