- type: job
  id: ESPassenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: ESJobPassenger
  startingGear: ESPassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: ESPassengerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpack