- type: job
  id: ESReporter
  name: job-name-reporter
  description: job-description-reporter
  suffix: ES
  playTimeTracker: ESJobReporter
  startingGear: ESReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ESReporterGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: ReporterPDA
    ears: ClothingHeadsetService
    head: ClothingHeadHatFedoraGrey
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpack

- type: chameleonOutfit
  id: ESReporterChameleonOutfit
  job: ESReporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitReporter
